#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting Music Player Daemon"
    [ ! -d /var/run/mpd_null ] && install -d -g 45 -o 45 /var/run/mpd_null
    /usr/bin/mpd /etc/mpd_null.conf &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon mpd_null
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Music Player Daemon"
    /usr/bin/mpd --kill /etc/mpd_null.conf &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon mpd_null
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
