#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/bin/mpdscribble9900`
case "$1" in
  start)
    stat_busy "Starting mpdscribble9900"
    [ -z "$PID" ] && /usr/bin/mpdscribble --port 9900 &
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /var/run/mpdscribble9900.pid
      add_daemon mpdscribble9900
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping mpdscribble9900 -- $PID"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm /var/run/mpdscribble9900.pid
      rm_daemon mpdscribble9900
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
